[general]
ipc_socket = true
import = ["~/.config/alacritty/everforest_dark.toml"]

[font]
size = 16
normal = { family = "Monaspace Xenon NF", style = "Regular" }
bold = { family = "Monaspace Xenon NF", style = "Bold" }
italic = { family = "Monaspace Xenon NF", style = "Italic" }

[bell]
animation = "Linear"
duration = 120
color = "#ff0000"
command = { program = "osascript", args = ["-e", "beep"] }

[terminal]
osc52 = "OnlyCopy"

[scrolling]
history = 50000
multiplier = 3

[mouse]
hide_when_typing = true

[window]
decorations = "Buttonless"
padding = { x = 4, y = 4 }
startup_mode = "Maximized"
option_as_alt = "OnlyRight"
